"""
Predictive Utility Evaluation
==============================

Project
-------
Synthetic Data Generation and Predictive Utility Evaluation
for Primary Biliary Cirrhosis (PBC) — Mayo Clinic Dataset

Purpose of this module
-----------------------
A synthetic dataset is only truly useful if models trained with it perform
at least as well as models trained on real data alone. Distributional fidelity
metrics like FID tell us whether the synthetic data looks statistically similar
to the real data, but they do not tell us whether the synthetic data is useful
for the task we actually care about, which is predicting patient outcomes.

This module evaluates predictive utility by training classifiers under the
real-data and synthetic-only scenarios (A, B, C, D, E) and measuring their
performance on a held-out real test set.

N_Days leakage
    N_Days is the number of days from registration to the earlier of death,
    transplantation, or end of study. It is not a baseline covariate: it is
    the follow-up duration, and it is defined jointly with Status. Using it
    as an input feature to predict Status leaks the outcome, since Status
    is derived from whether the deceased event fell within N_Days at all.
    By default every scenario here trains on CLASSIFICATION_FEATURE_COLS
    (ALL_FEATURE_COLS with N_Days removed), not ALL_FEATURE_COLS. N_Days is
    still generated by the upstream generative models — it remains
    available as a duration for the landmark and survival-analysis
    framings — it is excluded only from the classifier's input features.

Training scenarios
    Scenario A: Baseline
        The classifier is trained only on the real training patients.
        This is the reference point against which we compare augmented training.

    Scenario B: Real plus filtered cGAN
        The real training patients are combined with the IQR-filtered cGAN
        synthetic records before training. We use cGAN specifically here
        because it achieved the best FID score among the three individual methods.

    Scenario C: Real plus consensus synthetic
        The real training patients are combined with the consensus synthetic
        records. The consensus set is expected to be the highest quality subset
        because it was endorsed by all three generative models.

    Scenario D: Real plus SMOTE (classical baseline)
        Computed by run_smote_scenario(): the real training patients are
        augmented with SMOTE oversampling. This provides a classical
        interpolation baseline against the deep generative scenarios.

    Scenario E: Synthetic data only
        The classifier is trained exclusively on filtered synthetic records
        with no real training patients included, and evaluated on real
        held-out patients (train-on-synthetic, test-on-real / TSTR). This
        scenario acts as the synthetic-only baseline and answers the
        question: how well does a model generalise to real patients when it
        has never seen any real training data? It is the direct counterpart
        to Scenario A. run_scenario_e_multi() runs this for an arbitrary set
        of generators (not just cGAN), so FID can be plotted against TSTR
        AUC across all of them.

Test set rule
    The test set is always and only composed of real patients. It is never
    contaminated with synthetic data. This is essential for a fair comparison:
    we want to know how well the model generalises to real future patients, not
    how well it performs on synthetic ones.

Classifiers evaluated
    Random Forest: an ensemble of decision trees that is robust to feature
    scale and naturally handles mixed feature types.

    Gradient Boosting: a sequential ensemble that often achieves the highest
    accuracy on tabular data by correcting the errors of previous trees.

    Logistic Regression: a linear model that provides an interpretable baseline
    and is useful for assessing whether the prediction problem is linearly
    separable.

Performance metrics
    Accuracy: proportion of test patients correctly classified.
    F1 Score: harmonic mean of precision and recall, weighted by class support.
    Precision: of the patients predicted to be deceased, how many actually were.
    Recall: of the patients who were actually deceased, how many were correctly predicted.
    AUC: area under the ROC curve, measuring discrimination across all thresholds.
"""

import numpy as np
import pandas as pd

from sklearn.ensemble       import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model   import LogisticRegression
from sklearn.metrics        import (accuracy_score, f1_score,
                                    precision_score, recall_score,
                                    roc_auc_score)
from sklearn.preprocessing  import StandardScaler
from imblearn.over_sampling import SMOTE

from .data_loader import (TARGET_COL, ALL_FEATURE_COLS,
                          CLASSIFICATION_FEATURE_COLS, landmark_label)


def _build_classifiers():
    """
    Instantiate the three classifiers with fixed hyperparameters.

    The random state is fixed at 42 throughout to ensure all results are
    reproducible. The hyperparameters chosen here are standard configurations
    known to work well on small to medium tabular datasets without tuning.
    """
    return {
        "Random Forest": RandomForestClassifier(
            n_estimators=200, random_state=42, n_jobs=-1
        ),
        "Gradient Boosting": GradientBoostingClassifier(
            n_estimators=200, max_depth=3, random_state=42
        ),
        "Logistic Regression": LogisticRegression(
            max_iter=1000, random_state=42, solver="lbfgs"
        ),
    }


def _evaluate_one_classifier(clf, X_train, y_train, X_test, y_test):
    """
    Train a single classifier and evaluate it on the test set.

    Parameters
    ----------
    clf             : a scikit-learn classifier instance
    X_train, y_train: training features and labels
    X_test, y_test  : test features and labels (always real patients)

    Returns
    -------
    metrics : dictionary with Accuracy, F1, Precision, Recall, and AUC.
              All metrics are NaN if y_train contains only one class: this
              happens for some generator pools under the landmark framing
              (a generator's synthetic N_Days/Status distribution can fall
              entirely on one side of the horizon), and no classifier can
              be fit in that case. This is reported as a NaN result rather
              than raised as an error, since it is itself a real finding
              about that generator's synthetic time-to-event distribution.
    """
    if len(np.unique(y_train)) < 2:
        print("    WARNING: training labels contain only one class "
              "(no event or no non-event records) — classifier cannot be "
              "fit; reporting NaN for this (scenario, classifier).")
        return {"Accuracy": np.nan, "F1": np.nan, "Precision": np.nan,
                "Recall": np.nan, "AUC": np.nan}

    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    try:
        y_prob = clf.predict_proba(X_test)
        if y_prob.shape[1] == 2:
            auc = roc_auc_score(y_test, y_prob[:, 1])
        else:
            auc = roc_auc_score(y_test, y_prob, multi_class="ovr", average="macro")
    except Exception:
        auc = np.nan

    return {
        "Accuracy":  round(accuracy_score(y_test, y_pred), 4),
        "F1":        round(f1_score(y_test, y_pred, average="weighted",
                                    zero_division=0), 4),
        "Precision": round(precision_score(y_test, y_pred, average="weighted",
                                           zero_division=0), 4),
        "Recall":    round(recall_score(y_test, y_pred, average="weighted",
                                        zero_division=0), 4),
        "AUC":       round(auc, 4) if not np.isnan(auc) else np.nan,
    }


def run_all_scenarios(train_real, test_real, filtered_ctgan, consensus_df,
                       feat_cols=None, target_col=TARGET_COL,
                       scenario_b_name="B: Real data plus filtered cGAN",
                       scenario_e_name="E: Synthetic data only (cGAN filtered)"):
    """
    Run scenarios A, B, C, and E for all three classifiers.

    For each scenario we standardise the training features using a scaler
    fitted on that scenario's training data, and apply the same transformation
    to the test features. This prevents information about the test set from
    influencing the feature scaling.

    Parameters
    ----------
    train_real     : real training patients
    test_real      : real test patients, never used for training
    filtered_ctgan : IQR-filtered cGAN synthetic records for Scenario B and E
    consensus_df   : consensus synthetic records for Scenario C
    feat_cols      : input feature columns; defaults to
                      CLASSIFICATION_FEATURE_COLS (N_Days excluded, since
                      N_Days is jointly defined with the outcome and using
                      it as a classifier input leaks Status)
    target_col     : the column being predicted; defaults to TARGET_COL
                      ("Status"). Pass "landmark_event" for the fixed-horizon
                      framing (see run_landmark_scenarios).
    scenario_b_name, scenario_e_name : labels for the augmentation-source
                      dependent scenarios, so callers reusing this function
                      for a generator other than cGAN can relabel them.

    Returns
    -------
    results_df : pandas DataFrame with one row per (scenario, classifier) pair,
                 containing n_train, Accuracy, F1, Precision, Recall, and AUC
    """
    if feat_cols is None:
        feat_cols = CLASSIFICATION_FEATURE_COLS
    feat_cols = [c for c in feat_cols if c in train_real.columns]

    X_test = test_real[feat_cols].values
    y_test = np.round(test_real[target_col].values).astype(int)

    def combine_and_clean(*dataframes):
        """Concatenate DataFrames and remove any rows that still have missing values."""
        combined = pd.concat(list(dataframes), ignore_index=True)
        return combined.dropna(subset=feat_cols + [target_col])

    scenarios = {
        "A: Baseline (real data only)": train_real,
        scenario_b_name:                combine_and_clean(train_real, filtered_ctgan),
        "C: Real data plus consensus synthetic": combine_and_clean(train_real, consensus_df),
        scenario_e_name:                filtered_ctgan,
    }

    all_records = []

    for scenario_name, train_df in scenarios.items():
        X_train = train_df[feat_cols].values
        # Round then cast to int so floating-point near-zero values from
        # generative models (e.g. 2.8e-17 instead of 0) are treated as
        # binary class labels, not continuous regression targets.
        y_train = np.round(train_df[target_col].values).astype(int)

        # Fit the scaler on this scenario's training data only
        scaler    = StandardScaler()
        X_train_s = scaler.fit_transform(X_train)
        X_test_s  = scaler.transform(X_test)

        print(f"\n  Scenario: {scenario_name}")
        print(f"  Training set size: {len(train_df)}  |  Test set size: {len(test_real)}")

        for clf_name, clf in _build_classifiers().items():
            metrics = _evaluate_one_classifier(
                clf, X_train_s, y_train, X_test_s, y_test
            )
            row = {
                "Scenario":   scenario_name,
                "Classifier": clf_name,
                "n_train":    len(train_df),
                **metrics
            }
            all_records.append(row)
            print(f"    {clf_name:<22}  Accuracy {metrics['Accuracy']:.4f}  "
                  f"F1 {metrics['F1']:.4f}  AUC {metrics['AUC']}")

    return pd.DataFrame(all_records)


def run_smote_scenario(train_real, test_real, feat_cols=None,
                        target_col=TARGET_COL, random_state=42):
    """
    Scenario D: real training patients augmented with SMOTE oversampling.

    This is the classical interpolation baseline against the deep
    generative scenarios. SMOTE interpolates directly between real
    training records in feature space; it does not learn a generative
    model, so it has no synthetic-data quality controls (no IQR filter,
    no consensus, no FID) to apply.

    Parameters
    ----------
    train_real, test_real : as in run_all_scenarios
    feat_cols   : defaults to CLASSIFICATION_FEATURE_COLS
    target_col  : defaults to TARGET_COL; pass "landmark_event" for the
                  landmark framing
    random_state: SMOTE and classifier seed, fixed at 42 throughout

    Returns
    -------
    results_df : one row per classifier, same schema as run_all_scenarios
    """
    if feat_cols is None:
        feat_cols = CLASSIFICATION_FEATURE_COLS
    feat_cols = [c for c in feat_cols if c in train_real.columns]

    X_train = train_real[feat_cols].values
    y_train = np.round(train_real[target_col].values).astype(int)
    X_test  = test_real[feat_cols].values
    y_test  = np.round(test_real[target_col].values).astype(int)

    smote = SMOTE(random_state=random_state)
    X_res, y_res = smote.fit_resample(X_train, y_train)

    scaler    = StandardScaler()
    X_res_s   = scaler.fit_transform(X_res)
    X_test_s  = scaler.transform(X_test)

    all_records = []
    print(f"\n  Scenario: D: Real data plus SMOTE")
    print(f"  Training set size: {len(X_res)}  |  Test set size: {len(test_real)}")

    for clf_name, clf in _build_classifiers().items():
        metrics = _evaluate_one_classifier(clf, X_res_s, y_res, X_test_s, y_test)
        all_records.append({
            "Scenario":   "D: Real data plus SMOTE",
            "Classifier": clf_name,
            "n_train":    len(X_res),
            **metrics
        })
        print(f"    {clf_name:<22}  Accuracy {metrics['Accuracy']:.4f}  "
              f"F1 {metrics['F1']:.4f}  AUC {metrics['AUC']}")

    return pd.DataFrame(all_records)


def run_scenario_e_multi(train_real, test_real, generator_pools, feat_cols=None,
                          target_col=TARGET_COL):
    """
    Scenario E (train-on-synthetic, test-on-real) for an arbitrary set of
    generators, so FID can be plotted against TSTR AUC across all of them
    rather than asserting a relationship from cGAN alone.

    Parameters
    ----------
    train_real, test_real : as in run_all_scenarios (train_real is unused
                             for training here, since Scenario E trains
                             exclusively on synthetic data, but is kept for
                             a consistent call signature with the other
                             scenario runners and to make explicit that no
                             real record ever enters training)
    generator_pools : dict {generator_name: filtered_synthetic_df}, e.g.
                       {"Vanilla GAN": ..., "cGAN": ..., "VAE": ...,
                        "Masked-loss VAE": ..., "CTGAN": ...,
                        "Consensus": ...}
    feat_cols   : defaults to CLASSIFICATION_FEATURE_COLS
    target_col  : defaults to TARGET_COL; pass "landmark_event" for the
                  landmark framing (each pool must already carry that
                  column, e.g. via data_loader.landmark_label applied to
                  its own generated N_Days/Status)

    Returns
    -------
    results_df : one row per (generator, classifier), same metric columns
                 as run_all_scenarios, plus a "Generator" column
    """
    if feat_cols is None:
        feat_cols = CLASSIFICATION_FEATURE_COLS
    feat_cols = [c for c in feat_cols if c in test_real.columns]

    X_test = test_real[feat_cols].values
    y_test = np.round(test_real[target_col].values).astype(int)

    all_records = []
    for gen_name, pool_df in generator_pools.items():
        cols = [c for c in feat_cols if c in pool_df.columns]
        if len(cols) != len(feat_cols):
            missing = set(feat_cols) - set(cols)
            raise ValueError(f"Generator pool '{gen_name}' is missing columns {missing}")

        X_train = pool_df[feat_cols].values
        y_train = np.round(pool_df[target_col].values).astype(int)

        scaler    = StandardScaler()
        X_train_s = scaler.fit_transform(X_train)
        X_test_s  = scaler.transform(X_test)

        print(f"\n  Scenario E generator: {gen_name}")
        print(f"  Training set size: {len(pool_df)}  |  Test set size: {len(test_real)}")

        for clf_name, clf in _build_classifiers().items():
            metrics = _evaluate_one_classifier(clf, X_train_s, y_train, X_test_s, y_test)
            all_records.append({
                "Generator":  gen_name,
                "Scenario":   f"E: Synthetic data only ({gen_name})",
                "Classifier": clf_name,
                "n_train":    len(pool_df),
                **metrics
            })
            print(f"    {clf_name:<22}  Accuracy {metrics['Accuracy']:.4f}  "
                  f"F1 {metrics['F1']:.4f}  AUC {metrics['AUC']}")

    return pd.DataFrame(all_records)


def apply_landmark_frame(df, horizon_days):
    """
    Filter a frame to landmark-usable rows and attach a "landmark_event"
    column, for both real and synthetic frames (synthetic frames use their
    own generated N_Days/Status, so the label definition is applied
    identically on both sides of every scenario).

    Parameters
    ----------
    df           : DataFrame with N_Days and Status columns
    horizon_days : landmark horizon in days

    Returns
    -------
    filtered_df : copy of df restricted to usable rows, with an added
                  integer "landmark_event" column
    """
    usable, label = landmark_label(df, horizon_days)
    out = df.loc[usable].copy()
    out["landmark_event"] = label.loc[usable].values
    return out.reset_index(drop=True)


def run_landmark_scenarios(train_real, test_real, filtered_ctgan, consensus_df,
                            horizon_days, feat_cols=None):
    """
    Scenarios A, B, C, E under the fixed-horizon landmark framing: predict
    whether death occurs within `horizon_days`, among patients whose status
    at the horizon is actually known (see data_loader.landmark_label for
    why patients censored before the horizon are excluded rather than
    coded as survivors). This avoids both problems the reviewer raised:
    N_Days is excluded from feat_cols by default, and censoring before the
    horizon is dropped rather than silently coded as "survived".

    Returns
    -------
    results_df : same schema as run_all_scenarios, computed on the
                 landmark-filtered/relabeled cohort
    """
    train_lm     = apply_landmark_frame(train_real, horizon_days)
    test_lm      = apply_landmark_frame(test_real, horizon_days)
    ctgan_lm     = apply_landmark_frame(filtered_ctgan, horizon_days)
    consensus_lm = apply_landmark_frame(consensus_df, horizon_days)

    return run_all_scenarios(
        train_lm, test_lm, ctgan_lm, consensus_lm,
        feat_cols=feat_cols, target_col="landmark_event"
    )


def pivot_results(results_df, metric="F1"):
    """
    Rearrange the results table into a Scenario by Classifier grid.

    This format is convenient for inserting into a paper table or for
    generating a heatmap visualisation.

    Parameters
    ----------
    results_df : output of run_all_scenarios
    metric     : the performance metric to show in the grid cells

    Returns
    -------
    pivot table as a pandas DataFrame
    """
    return results_df.pivot(
        index="Scenario", columns="Classifier", values=metric
    ).round(4)
