"""
Synthetic Data Generator
========================

Project
-------
Synthetic Data Generation and Predictive Utility Evaluation
for Primary Biliary Cirrhosis (PBC) — Mayo Clinic Dataset

Purpose of this module
-----------------------
This module contains three generative model classes that learn the statistical
patterns of the real patient data and then produce new synthetic patient records
that resemble the original population. All three models are built using
TensorFlow 2 and operate on data that has been normalised to the range [0, 1].

The three models are described below.

Vanilla GAN (Generative Adversarial Network)
    A standard GAN as introduced by Goodfellow et al. (2014), adapted for
    tabular data. Two neural networks compete: the Generator learns to create
    realistic-looking fake patient records, and the Discriminator learns to
    tell real records apart from fake ones. Over many training epochs the
    Generator improves until the Discriminator can no longer reliably
    distinguish real from synthetic.

CTGAN (Conditional Tabular GAN)
    A conditional extension of the GAN where the Generator receives the
    patient outcome label (survived or died) as an additional input. This
    encourages the Generator to create realistic records for each class
    separately and helps maintain the correct class distribution in the
    synthetic output. Training uses balanced mini-batches so neither outcome
    dominates.

TVAE (Tabular Variational Autoencoder)
    A variational autoencoder that learns a compressed latent representation
    of the patient data. The Encoder maps each patient record to a point in
    latent space described by a mean and a variance. The Decoder reconstructs
    the record from a randomly sampled point near that location. New synthetic
    records are generated by sampling random points from the latent space and
    passing them through the Decoder. The training objective balances how well
    records are reconstructed against how closely the latent space follows a
    standard normal distribution.

Why all three?
    Each model has different strengths and weaknesses. Comparing them allows
    us to quantify which approach produces synthetic data that is most faithful
    to the original distribution and most useful for downstream prediction.

Input and output format
    All three models expect data that has been normalised with a Min-Max scaler
    (values in [0, 1]). After generation the caller should use the
    post_process_synthetic function from data_loader to restore original units
    and snap discrete columns to valid integer values.
"""

import os
import warnings
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


# Helper to select the right Adam optimizer.
# On Apple Silicon (M1 and M2) the legacy Adam is significantly faster
# because it avoids a known performance issue with the default TF 2.11+ Adam.
try:
    _AdamOptimizer = tf.keras.optimizers.legacy.Adam
except AttributeError:
    _AdamOptimizer = tf.keras.optimizers.Adam


class VanillaGAN:
    """
    Standard Generative Adversarial Network for tabular patient data.

    Architecture overview
        The Generator takes a random noise vector of fixed length (the latent
        dimension) and transforms it through two dense hidden layers into a
        vector of the same length as a patient record. The output activation
        is sigmoid so every generated value falls in [0, 1].

        The Discriminator takes a patient record (real or generated) and
        passes it through two dense hidden layers to produce a single number
        between 0 and 1 representing the probability that the record is real.
        Dropout layers regularise the Discriminator and prevent it from
        memorising specific training records.

        Both networks are trained with binary cross-entropy loss and the Adam
        optimiser with a learning rate of 0.0002 and a beta_1 of 0.5, which
        is the standard setting for GAN training.

    Parameters
    ----------
    latent_dim  : length of the random noise vector fed to the Generator
    epochs      : number of full passes through the training data
    batch_size  : number of samples per gradient update step
    lr          : learning rate for both optimisers
    print_every : print training progress every this many epochs
    """

    def __init__(self, latent_dim=100, epochs=500, batch_size=32,
                 lr=2e-4, print_every=100):
        self.latent_dim  = latent_dim
        self.epochs      = epochs
        self.batch_size  = batch_size
        self.lr          = lr
        self.print_every = print_every
        self.n_features  = None
        self.G = None
        self.D = None
        self.g_losses = []
        self.d_losses = []

    def _build_generator(self, n_features):
        """
        Build the Generator network.

        The network grows from the latent dimension upward through two hidden
        layers. Batch normalisation after each layer stabilises training.
        LeakyReLU activations allow small gradients when inputs are negative,
        which helps the Generator keep learning even when the Discriminator
        is dominant early in training.
        """
        model = keras.Sequential([
            layers.Input(shape=(self.latent_dim,)),
            layers.Dense(128),
            layers.LeakyReLU(0.2),
            layers.BatchNormalization(momentum=0.8),
            layers.Dense(256),
            layers.LeakyReLU(0.2),
            layers.BatchNormalization(momentum=0.8),
            layers.Dense(n_features, activation="sigmoid"),
        ], name="Generator")
        return model

    def _build_discriminator(self, n_features):
        """
        Build the Discriminator network.

        The network contracts from the input dimension down through two hidden
        layers to a single output score. Dropout layers are applied after each
        hidden layer to regularise the model and reduce overfitting to the
        small training set.
        """
        model = keras.Sequential([
            layers.Input(shape=(n_features,)),
            layers.Dense(256),
            layers.LeakyReLU(0.2),
            layers.Dropout(0.3),
            layers.Dense(128),
            layers.LeakyReLU(0.2),
            layers.Dropout(0.3),
            layers.Dense(1, activation="sigmoid"),
        ], name="Discriminator")
        return model

    def fit(self, X_scaled, verbose=True):
        """
        Train the GAN on normalised patient data.

        On each epoch we iterate through mini-batches. For each mini-batch
        we first update the Discriminator by showing it real samples labelled
        as 1 and freshly generated samples labelled as 0. We then update the
        Generator by asking it to fool the Discriminator, meaning we label its
        output as 1 and backpropagate the Discriminator's error.

        Parameters
        ----------
        X_scaled : numpy array of shape (n_patients, n_features) in [0, 1]
        verbose  : if True, print the generator and discriminator loss
                   every print_every epochs

        Returns
        -------
        self, so the call can be chained: gan.fit(data).generate(500)
        """
        self.n_features = X_scaled.shape[1]
        self.G = self._build_generator(self.n_features)
        self.D = self._build_discriminator(self.n_features)

        bce   = tf.keras.losses.BinaryCrossentropy()
        g_opt = _AdamOptimizer(self.lr, beta_1=0.5)
        d_opt = _AdamOptimizer(self.lr, beta_1=0.5)

        dataset = tf.data.Dataset.from_tensor_slices(
            X_scaled.astype(np.float32)
        ).shuffle(1000).batch(self.batch_size)

        for epoch in range(1, self.epochs + 1):
            g_loss_epoch = []
            d_loss_epoch = []

            for real_batch in dataset:
                batch_size = tf.shape(real_batch)[0]
                noise      = tf.random.normal((batch_size, self.latent_dim))
                fake       = self.G(noise, training=False)

                with tf.GradientTape() as tape:
                    d_real = self.D(real_batch, training=True)
                    d_fake = self.D(fake,       training=True)
                    d_loss = (bce(tf.ones_like(d_real),  d_real) +
                              bce(tf.zeros_like(d_fake), d_fake))
                grads = tape.gradient(d_loss, self.D.trainable_variables)
                d_opt.apply_gradients(zip(grads, self.D.trainable_variables))

                noise = tf.random.normal((batch_size, self.latent_dim))
                with tf.GradientTape() as tape:
                    fake   = self.G(noise, training=True)
                    d_out  = self.D(fake,  training=False)
                    g_loss = bce(tf.ones_like(d_out), d_out)
                grads = tape.gradient(g_loss, self.G.trainable_variables)
                g_opt.apply_gradients(zip(grads, self.G.trainable_variables))

                g_loss_epoch.append(float(g_loss))
                d_loss_epoch.append(float(d_loss))

            mean_g = np.mean(g_loss_epoch)
            mean_d = np.mean(d_loss_epoch)
            self.g_losses.append(mean_g)
            self.d_losses.append(mean_d)

            if verbose and epoch % self.print_every == 0:
                print(f"  Vanilla GAN  epoch {epoch:>4} of {self.epochs}  "
                      f"generator loss {mean_g:.4f}  discriminator loss {mean_d:.4f}")

        return self

    def generate(self, n_samples):
        """
        Generate n_samples synthetic patient records.

        Parameters
        ----------
        n_samples : number of records to produce

        Returns
        -------
        numpy array of shape (n_samples, n_features) with values in [0, 1]
        """
        noise = tf.random.normal((n_samples, self.latent_dim))
        return self.G(noise, training=False).numpy()


class CTGAN:
    """
    Conditional Tabular Generative Adversarial Network.

    This model extends the Vanilla GAN by conditioning both the Generator and
    the Discriminator on the patient outcome label (alive or died). The Generator
    receives both the random noise vector and a one-hot encoded class label as
    inputs, so it learns to generate records that are realistic for the specified
    outcome class. The Discriminator also receives the label so it judges whether
    a record is a plausible representative of its claimed class.

    During training we draw balanced mini-batches that contain equal numbers of
    survivors and non-survivors. This ensures the Generator practises both classes
    equally, which is important because the original dataset is somewhat imbalanced.

    When generating synthetic data we produce half the requested samples for
    each class and then shuffle them together.

    Parameters
    ----------
    latent_dim     : length of the random noise vector
    epochs         : training epochs
    batch_size     : samples per gradient step
    lr             : learning rate
    n_classes      : number of outcome classes (2 in our case: died and survived)
    target_col_idx : position of the Status column in the feature array
    print_every    : print progress every this many epochs
    """

    def __init__(self, latent_dim=100, epochs=300, batch_size=32, lr=2e-4,
                 n_classes=2, target_col_idx=-1, print_every=100):
        self.latent_dim   = latent_dim
        self.epochs       = epochs
        self.batch_size   = batch_size
        self.lr           = lr
        self.n_classes    = n_classes
        self.target_idx   = target_col_idx
        self.print_every  = print_every
        self.n_features   = None
        self.G = None
        self.D = None
        self.g_losses = []
        self.d_losses = []

    def _build_generator(self, n_features):
        """
        Build the conditional Generator.

        The Generator concatenates the noise vector with the class label before
        passing them through the hidden layers. This gives the Generator a direct
        signal about which outcome class it should be creating records for.
        """
        noise_input = layers.Input(shape=(self.latent_dim,), name="noise")
        label_input = layers.Input(shape=(self.n_classes,),  name="condition")
        x = layers.Concatenate()([noise_input, label_input])
        x = layers.Dense(128)(x)
        x = layers.LeakyReLU(0.2)(x)
        x = layers.BatchNormalization(momentum=0.8)(x)
        x = layers.Dense(256)(x)
        x = layers.LeakyReLU(0.2)(x)
        x = layers.BatchNormalization(momentum=0.8)(x)
        output = layers.Dense(n_features, activation="sigmoid")(x)
        return keras.Model([noise_input, label_input], output, name="CTGAN_Generator")

    def _build_discriminator(self, n_features):
        """
        Build the conditional Discriminator.

        The Discriminator also receives the class label so it can evaluate
        whether a record is realistic specifically for the claimed outcome class.
        """
        data_input  = layers.Input(shape=(n_features,),     name="data")
        label_input = layers.Input(shape=(self.n_classes,), name="condition")
        x = layers.Concatenate()([data_input, label_input])
        x = layers.Dense(256)(x)
        x = layers.LeakyReLU(0.2)(x)
        x = layers.Dropout(0.3)(x)
        x = layers.Dense(128)(x)
        x = layers.LeakyReLU(0.2)(x)
        x = layers.Dropout(0.3)(x)
        output = layers.Dense(1, activation="sigmoid")(x)
        return keras.Model([data_input, label_input], output, name="CTGAN_Discriminator")

    def _to_onehot(self, labels):
        """Convert an array of integer labels to one-hot vectors."""
        oh = np.zeros((len(labels), self.n_classes), dtype=np.float32)
        oh[np.arange(len(labels)), labels.astype(int)] = 1.0
        return oh

    def _balanced_batch(self, X, y, batch_size):
        """
        Sample a mini-batch with equal representation from each class.

        This ensures neither class dominates a batch, which keeps the
        Generator practising both kinds of records throughout training.
        """
        half   = batch_size // 2
        idx0   = np.where(y == 0)[0]
        idx1   = np.where(y == 1)[0]
        sample0 = np.random.choice(idx0, half, replace=(len(idx0) < half))
        sample1 = np.random.choice(idx1, half, replace=(len(idx1) < half))
        idx    = np.concatenate([sample0, sample1])
        np.random.shuffle(idx)
        return X[idx], y[idx]

    def fit(self, X_scaled, verbose=True):
        """
        Train the CTGAN on normalised patient data.

        The target (Status) column must be the last column in X_scaled or
        the column at position target_col_idx. Its values are rounded to
        0 or 1 to extract integer class labels for conditioning.

        Parameters
        ----------
        X_scaled : numpy array of shape (n_patients, n_features) in [0, 1]
        verbose  : if True, print training progress every print_every epochs

        Returns
        -------
        self
        """
        self.n_features = X_scaled.shape[1]
        self.G = self._build_generator(self.n_features)
        self.D = self._build_discriminator(self.n_features)

        y      = np.round(X_scaled[:, self.target_idx]).astype(int)
        bce    = tf.keras.losses.BinaryCrossentropy()
        g_opt  = _AdamOptimizer(self.lr, beta_1=0.5)
        d_opt  = _AdamOptimizer(self.lr, beta_1=0.5)

        for epoch in range(1, self.epochs + 1):
            g_loss_epoch = []
            d_loss_epoch = []
            n_batches    = max(1, len(X_scaled) // self.batch_size)

            for _ in range(n_batches):
                Xb, yb      = self._balanced_batch(X_scaled, y, self.batch_size)
                cond_real   = self._to_onehot(yb)

                # Generate fake records conditioned on randomly sampled labels
                fake_labels = np.random.randint(0, self.n_classes, len(Xb))
                cond_fake   = self._to_onehot(fake_labels)
                noise       = np.random.normal(0, 1, (len(Xb), self.latent_dim)).astype(np.float32)
                fake        = self.G([noise, cond_fake], training=False).numpy()

                with tf.GradientTape() as tape:
                    d_real = self.D([Xb.astype(np.float32), cond_real], training=True)
                    d_fake = self.D([fake,                  cond_fake], training=True)
                    d_loss = (bce(tf.ones_like(d_real),  d_real) +
                              bce(tf.zeros_like(d_fake), d_fake))
                grads = tape.gradient(d_loss, self.D.trainable_variables)
                d_opt.apply_gradients(zip(grads, self.D.trainable_variables))

                noise2       = np.random.normal(0, 1, (len(Xb), self.latent_dim)).astype(np.float32)
                fake_labels2 = np.random.randint(0, self.n_classes, len(Xb))
                cond_fake2   = self._to_onehot(fake_labels2)
                with tf.GradientTape() as tape:
                    fake2  = self.G([noise2, cond_fake2], training=True)
                    d_out2 = self.D([fake2,  cond_fake2], training=False)
                    g_loss = bce(tf.ones_like(d_out2), d_out2)
                grads = tape.gradient(g_loss, self.G.trainable_variables)
                g_opt.apply_gradients(zip(grads, self.G.trainable_variables))

                g_loss_epoch.append(float(g_loss))
                d_loss_epoch.append(float(d_loss))

            mean_g = np.mean(g_loss_epoch)
            mean_d = np.mean(d_loss_epoch)
            self.g_losses.append(mean_g)
            self.d_losses.append(mean_d)

            if verbose and epoch % self.print_every == 0:
                print(f"  CTGAN  epoch {epoch:>4} of {self.epochs}  "
                      f"generator loss {mean_g:.4f}  discriminator loss {mean_d:.4f}")

        return self

    def generate(self, n_samples):
        """
        Generate n_samples synthetic patient records in a balanced way.

        Half the samples are generated with the survivor label (0) and the
        other half with the deceased label (1), then the two groups are
        shuffled together. This preserves a roughly equal class distribution
        in the synthetic output before IQR filtering adjusts the counts.

        Parameters
        ----------
        n_samples : total number of synthetic records to produce

        Returns
        -------
        numpy array of shape (n_samples, n_features) with values in [0, 1]
        """
        half   = n_samples // 2
        parts  = []
        for label in [0, 1]:
            n      = half if label == 0 else (n_samples - half)
            noise  = np.random.normal(0, 1, (n, self.latent_dim)).astype(np.float32)
            cond   = self._to_onehot(np.full(n, label))
            gen    = self.G([noise, cond], training=False).numpy()
            parts.append(gen)
        out = np.vstack(parts)
        np.random.shuffle(out)
        return out


class TVAE:
    """
    Tabular Variational Autoencoder for patient data generation.

    The TVAE learns a probabilistic mapping from the space of patient records
    to a lower-dimensional latent space. Unlike a GAN, there is no adversarial
    training. Instead the model minimises a loss that combines reconstruction
    quality with a regularisation term that pushes the latent space toward a
    standard normal distribution.

    How generation works
        After training, we sample a random point from the standard normal
        distribution and pass it through the Decoder to obtain a synthetic
        patient record. Because the Decoder has learned to map normally
        distributed points back to realistic patient records, this produces
        new samples that resemble the training population.

    The training objective (ELBO)
        The Evidence Lower Bound combines two terms.
        The reconstruction term measures how well the Decoder reproduces the
        original record from the latent code, measured as mean squared error.
        The KL divergence term measures how much the learned latent distribution
        deviates from a standard normal, which prevents the latent space from
        collapsing or becoming too irregular for sampling.

    Parameters
    ----------
    latent_dim  : dimension of the latent space
    epochs      : training epochs
    batch_size  : samples per gradient step
    lr          : learning rate for the Adam optimiser
    beta        : weight on the KL divergence term
    print_every : print progress every this many epochs
    """

    def __init__(self, latent_dim=32, epochs=300, batch_size=32,
                 lr=1e-3, beta=1.0, print_every=100):
        self.latent_dim  = latent_dim
        self.epochs      = epochs
        self.batch_size  = batch_size
        self.lr          = lr
        self.beta        = beta
        self.print_every = print_every
        self.encoder     = None
        self.decoder     = None
        self.n_features  = None
        self.losses      = []

    def _build_encoder(self, n_features):
        """
        Build the Encoder network.

        The Encoder compresses a patient record into two vectors: the mean
        and the log-variance of the corresponding latent distribution. These
        two vectors together define a Gaussian distribution in latent space
        from which we can sample a specific latent code.
        """
        inp     = layers.Input(shape=(n_features,))
        x       = layers.Dense(128, activation="relu")(inp)
        x       = layers.Dense(64,  activation="relu")(x)
        mu      = layers.Dense(self.latent_dim)(x)
        log_var = layers.Dense(self.latent_dim)(x)
        return keras.Model(inp, [mu, log_var], name="TVAE_Encoder")

    def _build_decoder(self, n_features):
        """
        Build the Decoder network.

        The Decoder expands a latent code back into a full patient record.
        The sigmoid output activation ensures every reconstructed value falls
        in [0, 1], matching the normalised input format.
        """
        inp    = layers.Input(shape=(self.latent_dim,))
        x      = layers.Dense(64,  activation="relu")(inp)
        x      = layers.Dense(128, activation="relu")(x)
        output = layers.Dense(n_features, activation="sigmoid")(x)
        return keras.Model(inp, output, name="TVAE_Decoder")

    @staticmethod
    def _reparameterise(mu, log_var):
        """
        Apply the reparameterisation trick to sample from the latent distribution.

        Instead of sampling directly (which would block gradient flow), we
        sample a noise vector from the standard normal and then scale and shift
        it using the learned mean and variance. This keeps the operation
        differentiable with respect to the mean and variance parameters.
        """
        epsilon = tf.random.normal(tf.shape(mu))
        return mu + tf.exp(0.5 * log_var) * epsilon

    def fit(self, X_scaled, verbose=True):
        """
        Train the TVAE on normalised patient data.

        On each mini-batch we pass the data through the Encoder to obtain the
        latent mean and log-variance, sample a latent code using the
        reparameterisation trick, decode the sample back into the input space,
        and compute the combined reconstruction and KL divergence loss.

        Parameters
        ----------
        X_scaled : numpy array of shape (n_patients, n_features) in [0, 1]
        verbose  : if True, print the total loss every print_every epochs

        Returns
        -------
        self
        """
        self.n_features  = X_scaled.shape[1]
        self.encoder     = self._build_encoder(self.n_features)
        self.decoder     = self._build_decoder(self.n_features)

        opt     = _AdamOptimizer(self.lr)
        dataset = tf.data.Dataset.from_tensor_slices(
            tf.constant(X_scaled.astype(np.float32))
        ).shuffle(1000).batch(self.batch_size)

        for epoch in range(1, self.epochs + 1):
            epoch_losses = []

            for batch in dataset:
                with tf.GradientTape() as tape:
                    mu, log_var = self.encoder(batch,    training=True)
                    z           = self._reparameterise(mu, log_var)
                    x_hat       = self.decoder(z,         training=True)

                    reconstruction = tf.reduce_mean(tf.square(batch - x_hat))
                    kl_divergence  = -0.5 * tf.reduce_mean(
                        1 + log_var - tf.square(mu) - tf.exp(log_var)
                    )
                    total_loss = reconstruction + self.beta * kl_divergence

                all_trainable = (self.encoder.trainable_variables +
                                 self.decoder.trainable_variables)
                grads = tape.gradient(total_loss, all_trainable)
                opt.apply_gradients(zip(grads, all_trainable))
                epoch_losses.append(float(total_loss))

            mean_loss = np.mean(epoch_losses)
            self.losses.append(mean_loss)

            if verbose and epoch % self.print_every == 0:
                print(f"  TVAE  epoch {epoch:>4} of {self.epochs}  "
                      f"total loss {mean_loss:.4f}")

        return self

    def generate(self, n_samples):
        """
        Generate n_samples synthetic patient records.

        We sample random points from the standard normal distribution in the
        latent space and pass them through the trained Decoder to obtain
        synthetic patient records in [0, 1].

        Parameters
        ----------
        n_samples : number of synthetic records to generate

        Returns
        -------
        numpy array of shape (n_samples, n_features) with values in [0, 1]
        """
        z = tf.random.normal((n_samples, self.latent_dim))
        return self.decoder(z, training=False).numpy()


def generate_synthetic(model, n_samples, scaler, col_order, post_process_fn):
    """
    Run a trained generative model and return a clean, properly scaled DataFrame.

    This helper function wraps the three-step process of generating scaled
    samples, wrapping them in a DataFrame with the correct column names, and
    applying the post-processing step that restores original measurement units
    and snaps discrete columns to valid integers.

    Parameters
    ----------
    model           : a fitted VanillaGAN, CTGAN, or TVAE instance
    n_samples       : number of synthetic records to produce
    scaler          : the fitted MinMaxScaler from the data loader
    col_order       : list of column names matching the scaler's feature order
    post_process_fn : the post_process_synthetic function from data_loader

    Returns
    -------
    pandas DataFrame of shape (n_samples, len(col_order)) in original units
    """
    scaled_array  = model.generate(n_samples)
    scaled_df     = pd.DataFrame(scaled_array, columns=col_order)
    return post_process_fn(scaled_df, scaler, col_order)
